server_connect_timeout: 5000
listeners:
- query_port: 25575
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - core
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 100
  tab_size: 60
  force_default_server: false
  motd: "              Proxy &8generated &7by &r\n              &3Dream&9Network &eSystem!"
  tab_list: GLOBAL_PING
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.send
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: 100
ip_forward: true
groups:
  Alexandre01:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: true
stats: 0db8a911-f773-495f-865c-f8761b1941d1
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  core:
    motd: "&1Don't Touch at me"
    address: localhost:1111
    restricted: false

