# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: project

    - name: Show extracted Maven project version
      run: echo ${{ steps.project.outputs.version }}     
    - name: Get version
      run: |
        VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
        echo "::set-output name=version::$VERSION"
      id: get_version
    - name: ls
      run: 'ls'
      id: ls  
    - name: Remove Deobfuscated Jar
      run: "find . -type f ! -name '*-prod.jar' -delete"
      id: remove
    - name: Create Dir
      run: mkdir staging && cp target/*-prod.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: stagging
        
    - name: Pushes to another repository
      id: push_directory
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'target/*'
        destination_repo: 'DreamNetworkCloud/DreamNetwork-CDN'
        destination_folder: 'hypervisor/builds/${{ steps.project.outputs.version }}'
        user_email: 'altata01@hotmail.com'
        user_name: 'DreamNetBot'
        commit_message: 'Sending new build'
